### ISSUE TITLE
Create Controller for 'User' Model

### ISSUE THREAD

**Issue by cstayyab** [team5star/HighFive#32]
We need a controller for User model to have well-defined functions for each user operation.

**Comment by cstayyab** [comment]
@Moz125 can you provide me a list of functions that would be required related to user profiling(Sign Up, Login, Account Recovery)
Some sample function names are as follows:
* `username_exists($username)`
* `email_exists($email)`
* `match_password($username, $salted_password)`

**Comment by moazzam-hameed-paracha** [comment]
Like as in a list of functions pre-made, or just their names, parameters, outputs, and description?

**Comment by cstayyab** [comment]
> Like as in a list of functions pre-made, or just their names, parameters, outputs, and description?

It would be good if you provide the description also but names, parameters and outputs will also do.

**Comment by moazzam-hameed-paracha** [comment]
will do boi!

**Comment by cstayyab** [comment]
Commenting on behalf of @Moz125 :

======================>SIGN_UP<=======================

1) username_exists($username)

@DESCRIPTION:-	Checks to see if the username is present in the db or not.
@parameters:-	$username	[String].
@returns:-	Boolean.

2) email_exists($email)

@DESCRIPTION:-	Checks to see if the email is present in the db or not.
@parameters:-	$email	[String].
@returns:-	Boolean.


3) confirm_password($password_1, $password_2)

@DESCRIPTION:-	Check if the two given passwords match.
@parameters:-	$password_1 [String],	$password_2 [String].
@returns:-	Boolean.


4) Create the user using the user class.
========================>LOGIN<========================
1) SAME AS ABOVE
2) SAME AS ABOVE


3) get_user_id($email)	

@DESCRIPTION:-	Get the uid of the user to make it eaiser in the long run, save it in a global variable to use after verification.
@parameters:-	$email	[String].
@returns:-	$uid	[int].

4) verify_password($uid, $stored_password, $entered_password)	

@DESCRIPTION:-	Verify the password entered by the user is correct.
@parameters:-	$uid	[int], $stored_password	[String], $entered_password	[String]
@returns:-	Boolean.


========================>AFTER LOGIN<====================
1) get_groups_id($uid)			

@DESCRIPTION:-	Get the ids of all the groups the user is a part of.
@parameters:-	$uid	[int]
@returns:-	$uid	list[int].


2) get_friends($uid)

@DESCRIPTION:-	Get the uids of all the friends the user has.
@parameters:-	$uid	[int]
@returns:-	$uid	list[int].


3) get_group_members($gid)

@DESCRIPTION:-	Get the uids of all the users in a group.
@parameters:-	$gid	[int]
@returns:-	$uid	list[int].


4) get_posts($uid)

@DESCRIPTION:-	Get the pids and aids of all the posts the user has.
@parameters:-	$uid	[int]
@returns:-	2d list[$pid	list[int],	$aid	list[int]].


5) get_attachments($aid)

@DESCRIPTION:-	Get the source links of all the attachments the user has.
@parameters:-	$aid	[int]
@returns:-	$path	list[String].


6) load_user_preferences($uid)


@DESCRIPTION:-	Get the list of preferences the user has.
@parameters:-	$uid	[int]
@returns:-	associative array having all preferences in key value pairs.


7) load_group_preferences($gid)

@DESCRIPTION:-	Get the list of preferences the group has.
@parameters:-	$gid	[int]
@returns:-	associative array having all preferences in key value pairs.
	
 ===================>RECOVERY<======================
1) password_reset($uid, $old, $new)

@DESCRIPTION:-	Resets the users password. 
@parameters:-	$uid	[int], $old	 [String], $new		[String]
@returns:-	associative array having all preferences in key value pairs.


2) generate_recovery_code($uid)	

@DESCRIPTION:-	Generates and Stores a recovery code in the db and also emails it to the user.
@parameters:-	$uid	[int]
@returns:-	Boolean depending on whether email sent or not.

**Comment by cstayyab** [comment]
@all-contributors please add @Moz125 for ideas
