### ISSUE TITLE
Adjustments for Main Page for users.

### ISSUE THREAD

**Issue by cstayyab** [team5star/HighFive#41]
There are some CSS/Style wise changes required such as  sizes of buttons and alignments.

The path to file is views/index.html the css file for this in css/hf_design.css  

Assigning to @Alijaffery5

**Comment by Alijaffery5** [comment]
Ok

**Comment by Alijaffery5** [comment]
Modifications done, modified/adjusted search bar and its button, post message buttons alignment and size adjusted, sidebar like hover and other alignments

**Comment by Alijaffery5** [comment]
check the pull request

**Comment by cstayyab** [comment]
> 
> 
> check the pull request

PR #46 reviewed... check comments.

**Comment by cstayyab** [comment]
Solved in PR #46
